export const SYMBOL_NAMES: Record<string, string> = {
  high1: "Vinyl",
  high2: "Headphones",
  high3: "Cassette",
  high4: "Microphone",
  high5: "Amp",
  low1: "Speaker",
  low2: "Note",
  low3: "Equalizer",
  low4: "Palm",
  low5: "Cocktail",
  H1: "Vinyl",
  H2: "Headphones",
  H3: "Cassette",
  H4: "Microphone",
  H5: "Amp",
  L1: "Speaker",
  L2: "Note",
  L3: "Equalizer",
  L4: "Palm",
  L5: "Cocktail",
  wild: "Mixer",
  scatter: "Sunset",
  W: "Mixer",
  S: "Sunset",
  xWays: "xWays",
  xNudge: "xNudge",
};
