export const SYMBOL_NAMES: Record<string, string> = {
  high1: "Vinyl",
  high2: "Headphones",
  high3: "Cassette",
  high4: "Microphone",
  high5: "Amp",
  low1: "Speaker",
  low2: "Note",
  low3: "Equalizer",
  low4: "Palm",
  low5: "Cocktail",
  wild: "Mixer",
  scatter: "Sunset",
  xWays: "xWays",
  xNudge: "xNudge",
};
